apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  containers:
    - name: task-pv-container
      image: nginx:1.31.3
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: my-first-pvc
