apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retain-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # Created by retain-storageclass.yaml, which you apply first. The class has
  # to be a Retain one, or deleting this claim takes the disk with it.
  storageClassName: civo-volume-retain
  resources:
    requests:
      storage: 1Gi
